# Generated by Django 6.0.1 on 2026-02-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personuser',
            old_name='is_sttaf',
            new_name='is_staff',
        ),
        migrations.AddField(
            model_name='personuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
