# Generated by Django 6.0.1 on 2026-02-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_is_sttaf_personuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
