# Generated by Django 6.0.1 on 2026-02-26 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.customer'),
        ),
    ]
