# Generated by Django 6.0.1 on 2026-06-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Processing'), (2, 'Shipping'), (-1, 'Fail'), (-2, 'Other Fail'), (0, 'Pending')], default=-1),
        ),
    ]
