# Generated by Django 6.0.1 on 2026-06-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannermain',
            options={'ordering': ['-is_cover', 'order'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AddField(
            model_name='bannermain',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bannermain',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bannermain',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
